# Generated by Django 3.2.3 on 2021-05-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_items_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='host',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
