# Generated by Django 3.2.3 on 2021-05-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_items_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='host',
        ),
    ]
