# Generated by Django 3.2.3 on 2021-05-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_items_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='article_type',
        ),
        migrations.RemoveField(
            model_name='items',
            name='base_color',
        ),
        migrations.RemoveField(
            model_name='items',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='items',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='items',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='items',
            name='season',
        ),
        migrations.RemoveField(
            model_name='items',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='items',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='items',
            name='year',
        ),
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
